version: "3"
services: 
    portianer:
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        image: portainer/portainer
        volumes: 
            - portainer_vol:/data
            - /var/run/docker.sock:/var/run/docker.sock
        environment: 
            VIRTUAL_HOST: ${DOMAINS}
        ports: 
            - "9000:9000"
volumes: 
    portainer_vol: